### ISSUE TITLE
Market data error

### ISSUE THREAD

**Issue by abitmore** [blocksights/blocksights-open-explorer#3]
The data on https://blocksights.info/#/markets is clearly wrong.
(btw why 128 hours? It does not make sense to me.)

![image](https://user-images.githubusercontent.com/9946777/145675007-3654802e-1251-4907-b60d-2828cec924e5.png)

And the chart on the main page too.
![image](https://user-images.githubusercontent.com/9946777/145675269-a06f658c-d169-430c-926a-412ba43d6174.png)

At the same time, data on reference UI:
![image](https://user-images.githubusercontent.com/9946777/145675041-aa35aa98-0eb8-426b-b09a-5842c3a928e9.png)

Note: related to https://github.com/bitshares/bitshares-explorer-api/pull/80

**Comment by sschiessl-bcp** [comment]
Fixed landing page markets
![image](https://user-images.githubusercontent.com/33128181/147005472-242a8a25-00a5-4a3f-8919-ae72b48bccc7.png)

On markets page, no reason really, 128 was not so boring as doing 24 hours all the time. Maybe the 24hour average of the last 7 days? Fixed the sorting according to BTS equivalent base volume too
![image](https://user-images.githubusercontent.com/33128181/147005923-fed4c6dc-7c0d-4454-8790-474eaae46b05.png)
https://github.com/blocksights/blocksights-open-explorer/commit/17a10d5b035c871a7b9e4324173fb2ff8dd84438
