### ISSUE TITLE
Vesting balance issue

### ISSUE THREAD

**Issue by sschiessl-bcp** [blocksights/blocksights-open-explorer#33]
![image](https://user-images.githubusercontent.com/33128181/219490200-4c60214a-eb61-4b26-9b45-b6cfb0432b98.png)

https://blocksights.info/#/accounts/iobanker-core

https://blocksights.info/#/objects/1.13.27999

**Comment by ihorml** [comment]
@sschiessl-bcp should I take care of it?

**Comment by sschiessl-bcp** [comment]
https://github.com/blocksights/blocksights-open-explorer/commit/b76681bd12c23bca3e43508229abd40081beaa50
