### ISSUE TITLE
Missing weight_threshold in Authorities Tab.

### ISSUE THREAD

**Issue by freak5g** [blocksights/blocksights-open-explorer#35]
To reproduce:
1. Go to the #/accounts/committee-account
2. Click on the "Authorities" tab

Ubuntu: Firefox,
Android: Firefox

![auth](https://github.com/blocksights/blocksights-open-explorer/assets/87205099/63c1168f-510a-4603-be61-2506048507e0)

**Comment by sschiessl-bcp** [comment]
Thanks for the report. If you are interested, feel free to open a PR with expected behavior

**Comment by freak5g** [comment]
In the BitShares UI, the weight_threshold is referred to as "Threshold," and each account possesses a "Weight.
The expected behavior is that the user can see the threshold and weights.

| Account  | Weight |
|----------|--------|
| Bob      |   1    |
| Alice    |   1    |
| Charlie  |   1    |
| |Threshold: 2      |

**Comment by sschiessl-bcp** [comment]
Thanks @freak5g
